// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Actor
{
    public int IdActor { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int IdPais { get; set; }

    public virtual Pais IdPaisNavigation { get; set; }

    public virtual ICollection<PeliculasActor> PeliculasActores { get; set; } = new List<PeliculasActor>();
    public object NombreCompleto { get; internal set; }
}