// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Butaca
{
    public int IdButaca { get; set; }

    public int IdSala { get; set; }

    public int NumeroButaca { get; set; }

    public string Fila { get; set; }

    public int IdTipoButaca { get; set; }

    public virtual ICollection<ButacasFuncion> ButacasFuncions { get; set; } = new List<ButacasFuncion>();

    public virtual ICollection<DetalleReserva> DetalleReservas { get; set; } = new List<DetalleReserva>();

    public virtual Sala IdSalaNavigation { get; set; }

    public virtual TiposButaca IdTipoButacaNavigation { get; set; }
}