// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class ButacasFuncion
{
    public int IdButacaFuncion { get; set; }

    public int IdFuncion { get; set; }

    public int IdButaca { get; set; }

    public int? IdReserva { get; set; }

    public int? IdCompra { get; set; }

    public int IdEstadoButaca { get; set; }

    public virtual ICollection<DetallesCompra> DetallesCompras { get; set; } = new List<DetallesCompra>();

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual EstadoButaca IdEstadoButacaNavigation { get; set; }

    public virtual Funcion IdFuncionNavigation { get; set; }
}