// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Cine
{
    public int IdCine { get; set; }

    public string Nombre { get; set; }

    public int IdDireccion { get; set; }

    public string Telefono { get; set; }

    public virtual Direccion IdDireccionNavigation { get; set; }

    public virtual ICollection<Sala> Salas { get; set; } = new List<Sala>();
}