// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Compra
{
    public int IdCompra { get; set; }

    public int IdCliente { get; set; }

    public int IdFormaPago { get; set; }

    public DateTime FechaCompra { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<DetallesCompra> DetallesCompras { get; set; } = new List<DetallesCompra>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }
}