// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Descuento
{
    public int IdDescuento { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int IdTipoDescuento { get; set; }

    public decimal Valor { get; set; }

    public DateOnly? FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<FechasHorasEspecial> FechasHorasEspeciales { get; set; } = new List<FechasHorasEspecial>();

    public virtual TiposDescuento IdTipoDescuentoNavigation { get; set; }
}