// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class DetalleReserva
{
    public int IdDetalleReserva { get; set; }

    public int IdReserva { get; set; }

    public int IdButaca { get; set; }

    public int IdFuncion { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Funcion IdFuncionNavigation { get; set; }

    public virtual Reserva IdReservaNavigation { get; set; }
}