// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class DetallesCompra
{
    public int IdDetalleCompra { get; set; }

    public int IdCompra { get; set; }

    public int? IdFuncion { get; set; }

    public int? IdProducto { get; set; }

    public int? IdButacaFuncion { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual ButacasFuncion IdButacaFuncionNavigation { get; set; }

    public virtual Compra IdCompraNavigation { get; set; }

    public virtual Funcion IdFuncionNavigation { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }
}