// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Director
{
    public int IdDirector { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int IdPais { get; set; }

    public virtual Pais IdPaisNavigation { get; set; }

    public virtual ICollection<PeliculasDirector> PeliculasDirectores { get; set; } = new List<PeliculasDirector>();
}