// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Direccion
{
    public int IdDireccion { get; set; }

    public string Calle { get; set; }

    public string Numero { get; set; }

    public string Piso { get; set; }

    public int IdBarrio { get; set; }

    public virtual ICollection<Cine> Cines { get; set; } = new List<Cine>();

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual ICollection<PuntosVentum> PuntosVenta { get; set; } = new List<PuntosVentum>();
}