// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Distribuidora
{
    public int IdDistribuidora { get; set; }

    public string Nombre { get; set; }

    public int IdPais { get; set; }

    public virtual Pais IdPaisNavigation { get; set; }

    public virtual ICollection<Pelicula> Peliculas { get; set; } = new List<Pelicula>();
}