// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class EstadoReserva
{
    public int IdEstadoReserva { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}