// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class FechasEspecial
{
    public int IdFechaEspecial { get; set; }

    public DateOnly Fecha { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<FechasHorasEspecial> FechasHorasEspeciales { get; set; } = new List<FechasHorasEspecial>();
}