// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class FechasHorasEspecial
{
    public int IdFechaHoraEspecial { get; set; }

    public int IdFuncion { get; set; }

    public int? IdDescuento { get; set; }

    public int? IdFechaEspecial { get; set; }

    public TimeOnly Hora { get; set; }

    public virtual Descuento IdDescuentoNavigation { get; set; }

    public virtual FechasEspecial IdFechaEspecialNavigation { get; set; }

    public virtual Funcion IdFuncionNavigation { get; set; }
}