// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class FormasPago
{
    public int IdFormaPago { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Compra> Compras { get; set; } = new List<Compra>();
}