// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Funcion
{
    public int IdFuncion { get; set; }

    public int IdPelicula { get; set; }

    public int IdSala { get; set; }

    public DateTime FechaHoraInicio { get; set; }

    public decimal PrecioBase { get; set; }

    public virtual ICollection<ButacasFuncion> ButacasFuncions { get; set; } = new List<ButacasFuncion>();

    public virtual ICollection<DetalleReserva> DetalleReservas { get; set; } = new List<DetalleReserva>();

    public virtual ICollection<DetallesCompra> DetallesCompras { get; set; } = new List<DetallesCompra>();

    public virtual ICollection<FechasHorasEspecial> FechasHorasEspeciales { get; set; } = new List<FechasHorasEspecial>();

    public virtual Pelicula IdPeliculaNavigation { get; set; }

    public virtual Sala IdSalaNavigation { get; set; }
}