// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Idioma
{
    public int IdIdioma { get; set; }

    public string Nombre { get; set; }

    public bool Subtitulado { get; set; }

    public bool Doblado { get; set; }

    public virtual ICollection<PeliculasIdioma> PeliculasIdiomas { get; set; } = new List<PeliculasIdioma>();
}