// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Pais
{
    public int IdPais { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Actor> Actores { get; set; } = new List<Actor>();

    public virtual ICollection<Director> Directores { get; set; } = new List<Director>();

    public virtual ICollection<Distribuidora> Distribuidoras { get; set; } = new List<Distribuidora>();

    public virtual ICollection<Pelicula> Peliculas { get; set; } = new List<Pelicula>();

    public virtual ICollection<Provincia> Provincia { get; set; } = new List<Provincia>();
}