// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Pelicula
{
    public int IdPelicula { get; set; }

    public string Nombre { get; set; }
    public string Descripcion { get; set; }

    // Nueva columna para almacenar la ruta/URL de la imagen (varchar(300))
    public string Imagen { get; set; }

    public int Duracion { get; set; }

    public DateOnly? FechaEstreno { get; set; }

    public int IdClasificacion { get; set; }

    public int IdPais { get; set; }

    public int IdDistribuidora { get; set; }

    public int IdTipoPublico { get; set; }

    public virtual ICollection<Funcion> Funciones { get; set; } = new List<Funcion>();

    public virtual ClasificacionesPelicula IdClasificacionNavigation { get; set; }

    public virtual Distribuidora IdDistribuidoraNavigation { get; set; }

    public virtual Pais IdPaisNavigation { get; set; }

    public virtual TiposPublico IdTipoPublicoNavigation { get; set; }

    public virtual ICollection<PeliculasActor> PeliculasActores { get; set; } = new List<PeliculasActor>();

    public virtual ICollection<PeliculasDirector> PeliculasDirectores { get; set; } = new List<PeliculasDirector>();

    public virtual ICollection<PeliculasGenero> PeliculasGeneros { get; set; } = new List<PeliculasGenero>();

    public virtual ICollection<PeliculasIdioma> PeliculasIdiomas { get; set; } = new List<PeliculasIdioma>();
}