// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class PeliculasActor
{
    public int IdPeliActor { get; set; }

    public int IdPelicula { get; set; }

    public int IdActor { get; set; }

    public virtual Actor IdActorNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }
}