// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class PeliculasDirector
{
    public int IdPeliDirector { get; set; }

    public int IdPelicula { get; set; }

    public int IdDirector { get; set; }

    public virtual Director IdDirectorNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }
}