// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Producto
{
    public int IdProducto { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    // Nueva columna para almacenar la ruta/URL de la imagen (varchar(300))
    public string Imagen { get; set; }

    public decimal Precio { get; set; }

    public int IdTipoProducto { get; set; }

    public virtual ICollection<DetallesCompra> DetallesCompras { get; set; } = new List<DetallesCompra>();

    public virtual TiposProducto IdTipoProductoNavigation { get; set; }
}