// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Reserva
{
    public int IdReserva { get; set; }

    public int IdCliente { get; set; }

    public DateTime FechaHoraReserva { get; set; }

    public DateTime? FechaHoraVencimiento { get; set; }

    public int IdEstadoReserva { get; set; }

    public virtual ICollection<DetalleReserva> DetalleReservas { get; set; } = new List<DetalleReserva>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual EstadoReserva IdEstadoReservaNavigation { get; set; }
}