// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Sala
{
    public int IdSala { get; set; }

    public int IdCine { get; set; }

    public int NumeroSala { get; set; }

    public int Capacidad { get; set; }

    public int IdTipoSala { get; set; }

    public virtual ICollection<Butaca> Butacas { get; set; } = new List<Butaca>();

    public virtual ICollection<Funcion> Funciones { get; set; } = new List<Funcion>();

    public virtual Cine IdCineNavigation { get; set; }

    public virtual TiposSala IdTipoSalaNavigation { get; set; }
}