// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class TiposDescuento
{
    public int IdTipoDescuento { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Descuento> Descuentos { get; set; } = new List<Descuento>();
}