// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Email { get; set; }

    public int IdTipoUsuario { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public bool? Activo { get; set; }

    public int? IdEmpleado { get; set; }

    public int? IdCliente { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Empleado IdEmpleadoNavigation { get; set; }

    public virtual TiposUsuario IdTipoUsuarioNavigation { get; set; }
}